version: '3.8'

services:
  db:
    image: postgres:16
    container_name: lemnos-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lemnos-server
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      FIREBASE_CREDENTIALS: ${FIREBASE_CREDENTIALS}
      PORT: 8080
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  postgres_data: