INSERT INTO Estado(UF) VALUES
('AC'), ('AL'), ('AP'),
('AM'), ('BA'), ('CE'),
('ES'), ('GO'), ('MA'),
('MT'), ('MS'), ('MG'),
('PA'), ('PB'), ('PR'),
('PE'), ('PI'), ('RJ'),
('RN'), ('RS'), ('RO'),
('RR'), ('SC'), ('SP'),
('SE'), ('TO'), ('DF');

INSERT INTO Categoria VALUES
(0, 'Casa Inteligente'),
(1, 'Computadores'),
(2, 'Eletrônicos'),
(3, 'Hardware'),
(4, 'Kits'),
(5, 'Monitores'),
(6, 'Notebooks e Portáteis'),
(7, 'Periféricos'),
(8, 'Realidade Virtual'),
(9, 'Redes e wireless'),
(10, 'Video Games');

INSERT INTO Sub_Categoria VALUES
(0, 'Assistente Virtual', 0),
(1, 'Controles Smarts', 0),
(2, 'Lâmpadas Inteligentes', 0),
(3, 'Sensores', 0),
(4, 'Computadores Gamers', 1),
(5, 'Computadores Workstation', 1),
(6, 'Acessórios de Console', 2),
(7, 'Carregadores', 2),
(8, 'Refrigeração', 2),
(9, 'Smart Box', 2),
(10, 'Armazenamento', 3),
(11, 'Coolers', 3),
(12, 'Fonte', 3),
(13, 'Memória RAM', 3),
(14, 'Placa de Video', 3),
(15, 'Placa Mãe', 3),
(16, 'Processadores', 3),
(17, 'Gamer', 4),
(18, 'Periféricos', 4),
(19, 'Upgrade', 4),
(20, 'Monitores Gamers', 5),
(21, 'Monitores Workstation', 5),
(22, 'Notebooks', 6),
(23, 'Smartphones', 6),
(24, 'Tablets', 6),
(25, 'Caixa de Som', 7),
(26, 'Fone de Ouvido', 7),
(27, 'Microfone', 7),
(28, 'Mouse', 7),
(29, 'Mousepad', 7),
(30, 'Teclado', 7),
(31, 'Óculos de VR', 8),
(32, 'Periféricos DE VR', 8),
(33, 'Access Point', 9),
(34, 'Adaptadores', 9),
(35, 'Cabos', 9),
(36, 'Cabos de Redes', 9),
(37, 'Roteadores', 9),
(38, 'Switches', 9),
(39, 'Console de Mesa', 10),
(40, 'Portátil', 10);